### PR TITLE
Patch the shebang of files specifed with bin field

### PR DESCRIPTION
**Pull request by ilkecan**
Sometimes files specified with the bin field of package.json are missing
their executable bits when they are extracted[1]. npm must be setting their
executable bits at some stage of `npm install` life cycle because by the
time the command is complete, they are executable. But at "preinstall"
stage, which is when we patch the shebangs, those files are not
executable thus skipped by the `patchShebangs` function.

To fix this, `jq` is used to get the files specified with the "bin" field of
"package.json and the ones missing their executable bit are `chmod`'ed and patched.

[1]: E.g., `package/bin.js` extracted from https://registry.npmjs.org/prebuild-install/-/prebuild-install-6.0.1.tgz has its executable bit correctly set while the one from doesn't https://registry.npmjs.org/prebuild-install/-/prebuild-install-6.1.4.tgz

### CODE REVIEW

**Comment by ilkecan** [comment]
While trying to package https://github.com/eez-open/studio, using this commit patches 7 extra files, where at least one of those are used during the install. Without this commit, unpatched shebangs produces an error similar to
`sh: /build/node_modules/better-sqlite3/node_modules/.bin/prebuild-install: /usr/bin/env: bad interpreter: No such file or directory`.

**Comment by ilkecan** [comment]
Also somewhat related, currently this project uses [hook scripts](https://docs.npmjs.com/cli/v6/using-npm/scripts#hook-scripts) (specifically "preinstall" hook) to patch the shebangs. But as far as I can tell, hook scripts are removed from npm v7[1][2]. Do you have any plans to change the way shebangs are patched in a way that could also work with npm v7?

[1] https://github.com/npm/cli/issues/2692
[2] https://github.com/npm/cli/pull/3486

**Comment by ilkecan** [comment]
Wow, I didn't see https://github.com/nix-community/npmlock2nix/pull/107

**Comment by milahu** [comment]
> hook scripts are removed from npm v7

good to know!

we can run the lifecycle scripts manually

https://github.com/nix-community/npmlock2nix/blob/60b003cadaa90673f3ab43ff6aca5877f421b021/internal.nix#L288-L302

fixme: this does not-yet handle the case of a missing scripts field in package.json

**Comment by milahu** [comment]
> while were at it, we could fully replace `npm install` with [bash](https://github.com/basherpm/basher) scripts : P

much easier in javascript

https://github.com/milahu/npm-install-mini
forked from the lockfile parser https://github.com/npm/logical-tree

i use the same folder structure like pnpm (deep node_modules with symlinks),
but my "store" is in `node_modules/.pnpm`, not in `$HOME/.pnpm-store`

```
$ diff -rq node_modules.pnpm node_modules | grep ^Only

Only in node_modules.pnpm: .modules.yaml
Only in node_modules.pnpm/.pnpm: lock.yaml
Only in node_modules.pnpm/.pnpm: node_modules
```

works at least with cowsay ^^

<details>

```
$ npx cowsay "mooh!" -r
 _______
< mooh! >
 -------
 \
  \
 _   /|
 \'o.O'
 =(___)=
    U
```

</details>

**Comment by ilkecan** [comment]
@milahu I think GitHub stops sending notifications when a PR is closed. I read your comments by chance because this tab was left open. I opened [an issue](https://github.com/nix-community/npmlock2nix/issues/110) regarding the removal of hook scripts just now, to make it more visible. It was quite unlikely the maintainers would read these messages.

**Pull request closed without merging**
