### PR TITLE
WIP: Yarn support

### PR DESCRIPTION
**Pull request by andir**

### CODE REVIEW

**Comment by rgrinberg** [comment]
I'd like to second that it would be awesome to see support for this.

**Comment by milahu** [comment]
> I've a WIP rebase of this work (and some cleanup).

can you please share your wip?

**Comment by milahu** [comment]
see also

https://github.com/nix-community/dream2nix/blob/main/src/subsystems/nodejs/translators/yarn-lock/parser.nix

**Comment by andir** [comment]
This has severley bitrotted. I'll close this and we can pick this up another way / drop it entirely.

**Pull request closed without merging**
